import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: 'rgba(248, 250, 252, 1)' },

    filtersWrap: { paddingHorizontal: 16, paddingTop: 12, paddingBottom: 4 },
    typeChip: {
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 999,
        borderWidth: 1,
        borderColor: '#E5E7EB',
        backgroundColor: '#FFFFFF',
        marginRight: 8,
    },
    typeChipActive: { backgroundColor: '#111827', borderColor: '#111827' },
    typeChipText: { color: '#111827', fontWeight: '600' },
    typeChipTextActive: { color: '#FFFFFF' },

    segment: {
        flexDirection: 'row',
        backgroundColor: '#EEF2FF',
        borderRadius: 999,
        padding: 4,
        alignSelf: 'flex-start',
        marginTop: 6,
    },
    segmentBtn: { paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999 },
    segmentBtnActive: { backgroundColor: '#4338CA' },
    segmentText: { color: '#4338CA', fontWeight: '600' },
    segmentTextActive: { color: '#FFFFFF' },

    countWrap: { paddingHorizontal: 16, paddingVertical: 8 },
    countText: { color: '#6B7280', fontSize: 13 },

    card: {
        backgroundColor: '#FFFFFF',
        borderRadius: 14,
        overflow: 'hidden',
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: '#E5E7EB',
    },
    imageWrap: { position: 'relative' },
    image: { width: '100%', height: 160 },
    favBtn: {
        position: 'absolute',
        top: 10,
        right: 10,
        backgroundColor: '#FFFFFF',
        borderRadius: 999,
        padding: 6,
        elevation: 2,
    },
    badge: { position: 'absolute', top: 10, left: 10, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999 },
    badgeGreen: { backgroundColor: '#DCFCE7' },
    badgeGray: { backgroundColor: '#E5E7EB' },
    badgeText: { color: '#065F46', fontWeight: '700', fontSize: 12 },

    cardBody: { padding: 12 },
    rowBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    carName: { fontSize: 16, fontWeight: '700', color: '#0F172A', flexShrink: 1, paddingRight: 8 },
    carType: { fontSize: 12, fontWeight: '700', color: '#6B7280' },
    metaRow: { flexDirection: 'row', alignItems: 'center', marginTop: 6 },
    metaText: { marginLeft: 4, color: '#0F172A', fontWeight: '600' },
    metaSubText: { marginLeft: 4, color: '#6B7280' },
    featureChip: {
        borderWidth: 1,
        borderColor: '#E5E7EB',
        paddingHorizontal: 8,
        paddingVertical: 6,
        borderRadius: 999,
        marginRight: 8,
        backgroundColor: '#FFFFFF',
    },
    featureText: { color: '#111827', fontSize: 12, fontWeight: '600' },
    priceText: { fontSize: 16, fontWeight: '800', color: '#111827' },
    detailsBtn: { paddingHorizontal: 12, paddingVertical: 8, backgroundColor: '#111827', borderRadius: 10 },
    detailsText: { color: '#FFFFFF', fontWeight: '700' },
});
