import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    card: {
        backgroundColor: '#FFFFFF',
        borderRadius: 14,
        overflow: 'hidden',
        borderWidth: StyleSheet.hairlineWidth,
        borderColor: '#E5E7EB',
    },
    imageWrap: { position: 'relative' },
    image: { width: '100%', height: 160 },
    favBtn: {
        position: 'absolute',
        top: 10,
        right: 10,
        backgroundColor: '#FFFFFF',
        borderRadius: 999,
        padding: 6,
        elevation: 2,
    },
    badge: { position: 'absolute', top: 10, left: 10, paddingHorizontal: 10, paddingVertical: 6, borderRadius: 999 },
    badgeGreen: { backgroundColor: '#DCFCE7' },
    badgeGray: { backgroundColor: '#E5E7EB' },
    badgeText: { color: '#065F46', fontWeight: '700', fontSize: 12 },
    cardBody: { padding: 12 },
    rowBetween: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
    carName: { fontSize: 16, fontWeight: '700', color: '#0F172A', flexShrink: 1, paddingRight: 8 },
    carType: { fontSize: 12, fontWeight: '700', color: '#6B7280' },
    metaRow: { flexDirection: 'row', alignItems: 'center', marginTop: 6 },
    metaText: { marginLeft: 4, color: '#0F172A', fontWeight: '600' },
    metaSubText: { marginLeft: 4, color: '#6B7280' },
    featureChip: {
        borderWidth: 1,
        borderColor: '#E5E7EB',
        paddingHorizontal: 8,
        paddingVertical: 6,
        borderRadius: 999,
        marginRight: 8,
        backgroundColor: '#FFFFFF',
    },
    featureText: { color: '#111827', fontSize: 12, fontWeight: '600' },
    priceText: { fontSize: 16, fontWeight: '800', color: '#111827' },
    detailsBtn: { paddingHorizontal: 12, paddingVertical: 8, backgroundColor: '#111827', borderRadius: 10 },
    detailsText: { color: '#FFFFFF', fontWeight: '700' },
});
